version: '2'

networks: 
  hangtian:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.80.0/24
          gateway: 192.168.80.1
services:

  master.arclab.zju.edu.cn:
    build:
      context: ./
      dockerfile: Dockerfile2
    # image: hangtian:base
    container_name: master.arclab.zju.edu.cn
    #ports:
    #  - "7000:7000"
    #  - "7001:7001"
    environment:
      NODENAME: master
      ACCOUNTNAME: ACCOUNT1
      TLSNAME: TLS1
    networks: 
      #- hangtian
      hangtian:
        ipv4_address: 192.168.80.160
    command: bash -c "/calt/pca/server & \
             sleep 10 ; /calt/build/master 20001 master"
    # ./master <hosting port> <hosting name>


  client1.arclab.zju.edu.cn:
    build:
      context: ./
      dockerfile: Dockerfile2
    #  image: hangtian:base
    container_name: client1.arclab.zju.edu.cn
    environment:
      NODENAME: client1
      ACCOUNTNAME: ACCOUNT2
      TLSNAME: TLS2
    networks: 
      - hangtian
    command: bash -c "sleep 10 ; /calt/build/client 20001 master.arclab.zju.edu.cn 20001 client1"
    # ./client <hosting port> <target container_name> <target port> <hosting name>

  client2.arclab.zju.edu.cn:
    build:
      context: ./
      dockerfile: Dockerfile2
    #  image: hangtian:base
    container_name: client2.arclab.zju.edu.cn
    environment:
      NODENAME: client2
      ACCOUNTNAME: ACCOUNT3
      TLSNAME: TLS3
    networks: 
      - hangtian
    command: bash -c "sleep 10 ; /calt/build/client 20001 master.arclab.zju.edu.cn 20001 client2"    
    # ./client <hosting port> <target container_name> <target port> <hosting name>

  client3.arclab.zju.edu.cn:
    build:
      context: ./
      dockerfile: Dockerfile2
    #  image: hangtian:base
    container_name: client3.arclab.zju.edu.cn
    environment:
      NODENAME: client3
      ACCOUNTNAME: ACCOUNT4
      TLSNAME: TLS4
    networks: 
      - hangtian
    command: bash -c "sleep 10 ; /calt/build/client 20001 master.arclab.zju.edu.cn 20001 client3"
    # ./client <hosting port> <target container_name> <target port> <hosting name>

  client4.arclab.zju.edu.cn:
    build:
      context: ./
      dockerfile: Dockerfile2
    #  image: hangtian:base
    container_name: client4.arclab.zju.edu.cn
    environment:
      NODENAME: client4
      ACCOUNTNAME: ACCOUNT5
      TLSNAME: TLS5
    networks: 
      - hangtian
    command: bash -c "sleep 10 ; /calt/build/client 20001 master.arclab.zju.edu.cn 20001 client4"
    # ./client <hosting port> <target container_name> <target port> <hosting name>

  client5.arclab.zju.edu.cn:
    build:
      context: ./
      dockerfile: Dockerfile2
    #  image: hangtian:base
    container_name: client5.arclab.zju.edu.cn
    environment:
      NODENAME: client5
      ACCOUNTNAME: ACCOUNT6
      TLSNAME: TLS6
    networks: 
      - hangtian
    command: bash -c "sleep 10 ; /calt/build/client 20001 master.arclab.zju.edu.cn 20001 client5"
    # ./client <hosting port> <target container_name> <target port> <hosting name>

  client6.arclab.zju.edu.cn:
    build:
      context: ./
      dockerfile: Dockerfile2
    #  image: hangtian:base
    container_name: client6.arclab.zju.edu.cn
    environment:
      NODENAME: client6
      ACCOUNTNAME: ACCOUNT7
      TLSNAME: TLS7
    networks: 
      - hangtian
    command: bash -c "sleep 10 ; /calt/build/client 20001 master.arclab.zju.edu.cn 20001 client6"
    # ./client <hosting port> <target container_name> <target port> <hosting name>
    
